# Generated by Django 6.1.1 on 2026-09-25 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='equipped_frame',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='equipped_theme',
            field=models.CharField(blank=True, default='vs-dark', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='equipped_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_shields',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
