# Generated by Django 6.1.1 on 2026-09-11 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++'), ('java', 'Java')], max_length=20)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('runtime_error', 'Runtime Error'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('compilation_error', 'Compilation Error')], default='pending', max_length=32)),
                ('runtime', models.FloatField(blank=True, help_text='Runtime in ms', null=True)),
                ('memory', models.FloatField(blank=True, help_text='Memory in MB', null=True)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('test_results', models.JSONField(blank=True, default=list)),
                ('passed_tests', models.PositiveIntegerField(default=0)),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('is_run_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
