"use client";

import { create } from "zustand";

export type Language = "uz" | "en";

export const translations = {
  uz: {
    nav: {
      dashboard: "Boshqaruv",
      problems: "Masalalar",
      submissions: "Topshiriqlar",
      leaderboard: "Reyting",
      achievements: "Yutuqlar",
      profile: "Profil",
      settings: "Sozlamalar",
      admin: "Admin",
      shop: "Do'kon",
      invite: "Taklif",
      logout: "Chiqish",
      login: "Kirish",
      register: "Ro'yxatdan o'tish",
      getStarted: "Boshlash",
    },
    landing: {
      badge: "CodeArena 2.0 • Yangi avlod dasturlash maydoni",
      tagline: "Code. Compete. Level Up.",
      heroTitle1: "Kelajak dasturchilari",
      heroTitle2: "kod yozadigan va o'sadigan makon",
      subtitle: "Kod yozing, musobaqalashib darajangizni oshiring.",
      description:
        "Dunyo darajasidagi 30 ta algoritmik masalalar, professional Monaco IDE, real-vaqtda testlash va global reyting tizimi. Bugunoq o'z mahoratingizni sinovdan o'tkazing.",
      startCompeting: "Kodlashni boshlash — Bepul",
      browseProblems: "30 ta masalani ko'rish",
      exploreLeaderboard: "Yetakchilar reytingi",
      liveDemo: "Interaktiv namoyish",
      stats: {
        problems: "Masalalar",
        problemsVal: "30+",
        coders: "Faol dasturchi",
        codersVal: "1,500+",
        submissions: "Kod topshirig'i",
        submissionsVal: "12,000+",
        speed: "Sinov tezligi",
        speedVal: "< 30ms",
      },
      howItWorks: {
        badge: "Jarayon",
        title: "CodeArena qanday ishlaydi?",
        subtitle: "Oddiy 4 bosqichda dasturlash darajangizni oshiring va musobaqalarda g'olib bo'ling",
        step1Title: "Masalani tanlang",
        step1Desc: "Oson, o'rta yoki qiyin toifadagi 30 ta amaliy algoritmik masaladan birini tanlang.",
        step2Title: "Monaco IDE da kod yozing",
        step2Desc: "VS Code asosidagi professional muharrir, avtomatik to'ldirish va sintaksis yordami.",
        step3Title: "Bir zumda testdan o'ting",
        step3Desc: "Kodingiz xavfsiz muhitda yashirin va ochiq testlar bilan millisekundlarda tekshiriladi.",
        step4Title: "XP oling va cho'qqiga chiqing",
        step4Desc: "Har bir yechilgan masala uchun XP yig'ing, yangi darajalarga erishing va reytingda ko'tariling.",
      },
      ideSection: {
        badge: "Professional Muhit",
        title: "Brauzeringizda to'liq quvvatli kodlash studiyasi",
        subtitle: "Hech narsa o'rnatmasdan to'g'ridan-to'g'ri brauzeringizda kod yozing, test qiling va natijalarni darhol ko'ring.",
        editorTitle: "CodeArena Studio — two_sum.py",
        runBtn: "Kodni tekshirish",
        submitBtn: "Yechimni yuborish",
        acceptedStatus: "QABUL QILINDI (ACCEPTED)",
        testPassed: "Barcha test holatlari muvaffaqiyatli o'tdi",
        speedText: "Ishlash tezligi: 24 ms (98.6% tezroq)",
        memoryText: "Xotira: 14.1 MB",
        xpEarned: "+25 XP hisobingizga qo'shildi",
        terminalTab: "Natijalar",
        consoleTab: "Konsol",
      },
      difficultySection: {
        badge: "Darajalar",
        title: "Boshlang'ichdan professionalgacha",
        subtitle: "O'z darajangizga mos masalalarni tanlang va qiyinlikni asta-sekin oshirib boring",
        easy: "Oson daraja",
        easyXp: "+10 XP",
        easyDesc: "Massivlar, matnlar va asosiy qidiruv algoritmlari. Dasturlashga yangi kirganlar uchun ajoyib boshlanish.",
        medium: "O'rta daraja",
        mediumXp: "+25 XP",
        mediumDesc: "Dinamik dasturlash, daraxtlar, rekursiya va ikki ko'rsatkichli algoritmlar. Texnik intervyular uchun ideal.",
        hard: "Qiyin daraja",
        hardXp: "+50 XP",
        hardDesc: "Murakkab graf algoritmlari, segment daraxtlari va xotirani chuqur optimallashtirish talab qilinadigan masalalar.",
        solveAction: "Masalani yechish →",
      },
      features: {
        badge: "Imkoniyatlar",
        title: "Barcha kerakli vositalar bitta platformada",
        subtitle: "Dasturchilarning mahoratini oshirish uchun har bir detal chuqur o'ylangan",
        proIde: "Professional Monaco IDE",
        proIdeDesc: "VS Code muharririning barcha qulayliklari, qulay qisqa tugmalar va sintaksis yorug'ligi.",
        runner: "Xavfsiz Sandboxed Runner",
        runnerDesc: "Kodingiz xavfsiz izolyatsiyalangan konteynerda millisekundlar ichida bajariladi.",
        gamified: "Gamifikatsiya & XP Tizimi",
        gamifiedDesc: "Har bir to'g'ri javob uchun XP, kunlik streak olovi, 10 xil daraja va maxsus nishonlar.",
        leaderboard: "Jonli Global Reyting",
        leaderboardDesc: "O'zbekiston va butun dunyo dasturchilari bilan real vaqtda raqobatlashing.",
        analytics: "Batafsil Analitika & Tarix",
        analyticsDesc: "Qabul ko'rsatkichi, yuborilgan kodlar tarixi va qaysi toifalarda kuchli ekanligingizni kuzating.",
        bilingual: "Ikki Tilli Interfeys (UZ / EN)",
        bilingualDesc: "O'zbek tilida to'liq tushuntirilgan 30 ta masala va bir bosishda ingliz tiliga o'tish.",
      },
      leaderboardPreview: {
        badge: "Top Dasturchilar",
        title: "CodeArena Yetakchilari",
        subtitle: "Ushbu haftaning eng faol va yuqori natija ko'rsatgan dasturchilari",
        viewAll: "To'liq reytingni ko'rish →",
      },
      cta: {
        title: "Dasturlash mahoratingizni bugun yangi bosqichga olib chiqing",
        subtitle: "CodeArena'ga hoziroq qo'shiling, 30 ta algoritmik masalani yeching va yetakchilar safidan o'rin oling.",
        buttonPrimary: "Bepul hisob yaratish",
        buttonSecondary: "Masalalar ro'yxati",
      },
      footer: {
        description: "Dasturchilar uchun zamonaviy algoritmik musobaqa va o'rganish platformasi. Kod yozing, bellashing va o'sing.",
        platform: "Platforma",
        resources: "Resurslar",
        community: "Jamiyat",
        status: "Barcha tizimlar ishchi holatda (99.98%)",
        rights: "CodeArena. Barcha huquqlar himoyalangan.",
      },
    },
    dashboard: {
      welcomeBack: "Xush kelibsiz",
      keepStreak: "Ketma-ketlikni davom ettiring.",
      streakDays: "kunlik seriya",
      totalXp: "Umumiy XP",
      level: "Daraja",
      solved: "Yechilgan",
      submissions: "Topshiriqlar",
      streak: "Ketma-ketlik",
      globalRank: "Global o'rin",
      xpProgress: "XP Jarayoni",
      nextLevel: "Keyingi daraja",
      activity: "Faollik",
      todaysChallenge: "Bugungi Masala",
      startCoding: "Kodlashni boshlash",
      noChallenge: "Bugun uchun masala belgilanmagan.",
      quickActions: "Tezkor amallar",
      solveProblems: "Masalalar yechish",
      challengesAvailable: "ta masala tayyor",
      leaderboardAction: "Yetakchilar",
      leaderboardDesc: "Global reyting jadvali",
      submissionsAction: "Topshiriqlar",
      submissionsDesc: "Kod yuborishlar tarixi",
      profileAction: "Shaxsiy profil",
      profileDesc: "Statistika va nishonlar",
      featuredProblems: "Tavsiya etilgan masalalar",
      featuredDesc: "Dasturlash mahoratingizni oshiring",
      viewAllProblems: "Barcha 30 ta masala",
      recentSubmissions: "So'nggi topshiriqlar",
      noSubmissions: "Hozircha topshiriqlar yo'q. Masala yechishni boshlang!",
      solvedBadge: "Yechilgan",
      unsolvedBadge: "Yechilmagan",
      solveBtn: "Yechish",
    },
    problems: {
      title: "Dasturlash Masalalari",
      subtitle: "ta dasturlash masalalari mavjud",
      searchPlaceholder: "Masalalarni qidirish…",
      allDifficulties: "Barcha darajalar",
      allCategories: "Barcha toifalar",
      allStatus: "Barcha holatlar",
      easy: "Oson",
      medium: "O'rta",
      hard: "Qiyin",
      solvedOnly: "Faqat yechilganlar",
      unsolvedOnly: "Yechilmaganlar",
      statusCol: "Holat",
      titleCol: "Masala nomi",
      difficultyCol: "Qiyinlik",
      categoryCol: "Toifa",
      xpCol: "XP",
      acceptanceCol: "Qabul",
      actionCol: "Harakat",
      solveBtn: "Yechish →",
      prevPage: "Oldingi",
      nextPage: "Keyingi",
      page: "Sahifa",
    },
    workspace: {
      problemDesc: "Masala tavsifi",
      inputFormat: "Kiritish formati",
      outputFormat: "Chiqarish formati",
      examples: "Misollar",
      constraints: "Cheklovlar",
      input: "Kiritish",
      expectedOutput: "Kutilgan natija",
      explanation: "Tushuntirish",
      fontSize: "Shrift",
      copyCode: "Nusxalash",
      copied: "Nusxalandi!",
      resetCode: "Kodni tiklash",
      fullscreen: "To'liq ekran",
      testResults: "Test natijalari",
      console: "Konsol",
      runCode: "Kodni tekshirish",
      running: "Tekshirilmoqda…",
      submitCode: "Yechimni yuborish",
      submitting: "Yuborilmoqda…",
      accepted: "Qabul qilindi (Accepted)",
      wrongAnswer: "Noto'g'ri javob (Wrong Answer)",
      runtimeError: "Ishlashda xatolik (Runtime Error)",
      timeLimit: "Vaqt chegarasidan oshdi (Time Limit)",
      congrats: "Tabriklaymiz! Masala muvaffaqiyatli yechildi!",
      xpGained: "XP qo'shildi!",
      coinsGained: "coin",
      testCase: "Test holati",
      passed: "O'tdi",
      failed: "Yiqildi",
      expected: "Kutilgan",
      actual: "Haqiqiy",
      runtime: "Vaqt",
      memory: "Xotira",
    },
    leaderboard: {
      title: "Yetakchilar Jadvali",
      subtitle: "CodeArena dasturchilarining global reytingi",
      allTime: "Barcha vaqt",
      weekly: "Haftalik",
      monthly: "Oylik",
      searchUser: "Foydalanuvchini qidirish…",
      rank: "O'rin",
      coder: "Dasturchi",
      level: "Daraja",
      xp: "XP",
      solved: "Yechilgan",
      streak: "Seriya",
    },
    achievements: {
      title: "Yutuqlar va Nishonlar",
      subtitle: "Masalalar yechib maxsus daraja va yutuqlarni oching",
      unlocked: "Ochilgan",
      locked: "Qulflangan",
      progress: "Jarayon",
    },
    settings: {
      title: "Sozlamalar",
      subtitle: "Profilingiz va afzalliklaringizni boshqaring",
      languageSection: "Tizim tili",
      uzbekLang: "O'zbek tili (UZ)",
      englishLang: "English (EN)",
      preferredLanguage: "Asosiy dasturlash tili",
      bio: "O'zingiz haqingizda (Bio)",
      github: "GitHub profili",
      saveChanges: "O'zgarishlarni saqlash",
      saving: "Saqlanmoqda…",
      savedSuccess: "Sozlamalar muvaffaqiyatli saqlandi!",
    },
    profile: {
      title: "Profil",
      editSettings: "Sozlamalar",
      activity: "Yillik faollik",
      recentSubmissions: "So'nggi topshiriqlar",
      stats: "Statistika",
      acceptanceRate: "Qabul ko'rsatkichi",
    },
    submissions: {
      title: "Mening Topshiriqlarim",
      subtitle: "Barcha kod yuborishlar tarixi va natijalari",
      problem: "Masala",
      status: "Holat",
      language: "Til",
      runtime: "Vaqt",
      memory: "Xotira",
      date: "Sana",
    },
    auth: {
      loginTitle: "Tizimga kirish",
      loginSubtitle: "Musobaqani davom ettirish uchun hisobingizga kiring",
      registerTitle: "CodeArena'ga qo'shiling",
      registerSubtitle: "Dasturchi profilingizni yarating",
      username: "Foydalanuvchi nomi",
      email: "Email manzili",
      password: "Parol",
      signInBtn: "Kirish",
      signUpBtn: "Hisob yaratish",
      noAccount: "Hisobingiz yo'qmi?",
      alreadyAccount: "Hisobingiz bormi?",
      refCode: "Taklif kodi (ixtiyoriy)",
      refBonus: "Taklif kodi bilan qo'shilsangiz +100 coin bonus olasiz!",
    },
    shop: {
      title: "Coin Do'koni",
      subtitle: "Masala yechib coin yig'ing va ularni noyob buyumlarga almashtiring",
      balance: "Balansingiz",
      howToEarn: "Coin qanday topiladi?",
      earnEasy: "Oson masala",
      earnMedium: "O'rta masala",
      earnHard: "Qiyin masala",
      earnInvite: "Do'st taklif qilish",
      all: "Hammasi",
      frame: "Avatar ramkalari",
      title_: "Unvonlar",
      theme: "IDE mavzulari",
      booster: "Kuchaytirgichlar",
      buy: "Sotib olish",
      buying: "Olinmoqda…",
      owned: "Sizda bor",
      equip: "Kiyish",
      unequip: "Yechish",
      equipped: "Faol",
      notEnough: "Coin yetarli emas",
      history: "Coin tarixi",
      noHistory: "Hali coin harakatlari yo'q.",
      shields: "Streak qalqonlari",
      loginToBuy: "Sotib olish uchun tizimga kiring",
      rarity: { common: "Oddiy", rare: "Noyob", epic: "Epik", legendary: "Afsonaviy" },
    },
    referral: {
      title: "Do'stlarni taklif qiling",
      subtitle: "Har bir taklif qilingan do'st uchun +500 coin oling!",
      yourCode: "Sizning taklif kodingiz",
      yourLink: "Taklif havolangiz",
      copy: "Nusxalash",
      copied: "Nusxalandi!",
      step1: "Havolani do'stingizga yuboring",
      step2: "Do'stingiz ro'yxatdan o'tadi va +100 coin oladi",
      step3: "Siz darhol +500 coin olasiz",
      invited: "Taklif qilinganlar",
      earned: "Topilgan coin",
      friends: "Taklif qilgan do'stlaringiz",
      noFriends: "Hali hech kim taklifingiz bilan qo'shilmagan. Havolani ulashing!",
      joined: "qo'shildi",
    },
  },
  en: {
    nav: {
      dashboard: "Dashboard",
      problems: "Problems",
      submissions: "Submissions",
      leaderboard: "Leaderboard",
      achievements: "Achievements",
      profile: "Profile",
      settings: "Settings",
      admin: "Admin",
      shop: "Shop",
      invite: "Invite",
      logout: "Logout",
      login: "Log in",
      register: "Register",
      getStarted: "Get started",
    },
    landing: {
      badge: "CodeArena 2.0 • Next-Gen Competitive Platform",
      tagline: "Code. Compete. Level Up.",
      heroTitle1: "Where developers",
      heroTitle2: "code, compete & level up",
      subtitle: "Solve programming challenges, improve skills, and compete globally.",
      description:
        "Solve 30 real-world algorithm challenges with our professional Monaco IDE, sub-millisecond sandboxed test runner, and global ranking system.",
      startCompeting: "Start Coding — Free",
      browseProblems: "Browse 30 Problems",
      exploreLeaderboard: "Live Leaderboard",
      liveDemo: "Interactive Demo",
      stats: {
        problems: "Problems",
        problemsVal: "30+",
        coders: "Active Coders",
        codersVal: "1,500+",
        submissions: "Submissions",
        submissionsVal: "12,000+",
        speed: "Judge Latency",
        speedVal: "< 30ms",
      },
      howItWorks: {
        badge: "Workflow",
        title: "How CodeArena Works",
        subtitle: "Level up your algorithmic mastery and contest performance in 4 simple steps",
        step1Title: "Pick a Problem",
        step1Desc: "Choose from 30 curated challenges ranging from Easy foundations to Hard contest problems.",
        step2Title: "Code in Monaco IDE",
        step2Desc: "Full-featured VS Code-powered editor with auto-completion, keyboard shortcuts, and syntax colors.",
        step3Title: "Pass Instant Tests",
        step3Desc: "Your code is evaluated in isolated containers against sample and hidden test cases in milliseconds.",
        step4Title: "Earn XP & Rank Up",
        step4Desc: "Collect XP for every accepted solution, unlock prestigious badges, and climb the leaderboard.",
      },
      ideSection: {
        badge: "Pro Environment",
        title: "Full-powered coding studio in your browser",
        subtitle: "No setup required. Write, execute, and debug code directly in your browser with real-time test evaluations.",
        editorTitle: "CodeArena Studio — two_sum.py",
        runBtn: "Run Code",
        submitBtn: "Submit Solution",
        acceptedStatus: "ACCEPTED",
        testPassed: "All test cases passed successfully",
        speedText: "Runtime: 24 ms (Beats 98.6%)",
        memoryText: "Memory: 14.1 MB",
        xpEarned: "+25 XP added to your profile",
        terminalTab: "Test Results",
        consoleTab: "Console",
      },
      difficultySection: {
        badge: "Difficulties",
        title: "Problems for every skill level",
        subtitle: "From foundational data structures to competitive programming contest challenges",
        easy: "Easy Tier",
        easyXp: "+10 XP",
        easyDesc: "Arrays, strings, and fundamental two-pointer techniques. Perfect for building coding speed.",
        medium: "Medium Tier",
        mediumXp: "+25 XP",
        mediumDesc: "Dynamic programming, trees, graphs, and greedy algorithms. Essential for top-tier tech interviews.",
        hard: "Hard Tier",
        hardXp: "+50 XP",
        hardDesc: "Advanced data structures, complex DP, and optimal algorithmic performance under strict time limits.",
        solveAction: "Solve Challenge →",
      },
      features: {
        badge: "Capabilities",
        title: "Everything you need to master algorithms",
        subtitle: "Carefully designed developer tools to accelerate your coding journey",
        proIde: "Professional Monaco IDE",
        proIdeDesc: "VS Code powerhouse with dark theme, intelligent IntelliSense, and customizable font sizing.",
        runner: "Sandboxed Instant Runner",
        runnerDesc: "Execute Python, JavaScript, and C++ safely in high-speed isolated sandboxes in milliseconds.",
        gamified: "Gamification & XP Levels",
        gamifiedDesc: "Progressive XP system, daily streak flame, 10 competitive tiers, and unlockable achievements.",
        leaderboard: "Live Global Rankings",
        leaderboardDesc: "Compete with developers in real time and see your position on the worldwide scoreboard.",
        analytics: "Deep Analytics & History",
        analyticsDesc: "Track your acceptance rate, runtime percentiles, and category breakdown over time.",
        bilingual: "Dual Language (UZ / EN)",
        bilingualDesc: "Full native Uzbek and English translations across all 30 problems and UI interfaces.",
      },
      leaderboardPreview: {
        badge: "Top Coders",
        title: "CodeArena Hall of Fame",
        subtitle: "This week's most active and highest-ranked competitive programmers",
        viewAll: "View Full Leaderboard →",
      },
      cta: {
        title: "Ready to level up your engineering skills?",
        subtitle: "Join CodeArena today, conquer 30 challenges, and cement your place on the leaderboard. 100% free.",
        buttonPrimary: "Create Free Account",
        buttonSecondary: "Browse Problems",
      },
      footer: {
        description: "Modern competitive coding and algorithm mastery platform. Code. Compete. Level Up.",
        platform: "Platform",
        resources: "Resources",
        community: "Community",
        status: "All systems operational (99.98%)",
        rights: "CodeArena. All rights reserved.",
      },
    },
    dashboard: {
      welcomeBack: "Welcome back",
      keepStreak: "Keep the streak alive.",
      streakDays: "day streak",
      totalXp: "Total XP",
      level: "Level",
      solved: "Solved",
      submissions: "Submissions",
      streak: "Streak",
      globalRank: "Global Rank",
      xpProgress: "XP Progress",
      nextLevel: "Next level",
      activity: "Activity",
      todaysChallenge: "Today's Challenge",
      startCoding: "Start Coding",
      noChallenge: "No challenge set today.",
      quickActions: "Quick Actions",
      solveProblems: "Solve Problems",
      challengesAvailable: "challenges available",
      leaderboardAction: "Leaderboard",
      leaderboardDesc: "Global rankings",
      submissionsAction: "Submissions",
      submissionsDesc: "Code execution history",
      profileAction: "Profile",
      profileDesc: "Stats & Badges",
      featuredProblems: "Featured Problems",
      featuredDesc: "Practice and level up your skills",
      viewAllProblems: "All 30 Problems",
      recentSubmissions: "Recent Submissions",
      noSubmissions: "No submissions yet. Solve a problem!",
      solvedBadge: "Solved",
      unsolvedBadge: "Unsolved",
      solveBtn: "Solve",
    },
    problems: {
      title: "Coding Problems",
      subtitle: "challenges available",
      searchPlaceholder: "Search problems…",
      allDifficulties: "All difficulties",
      allCategories: "All categories",
      allStatus: "All status",
      easy: "Easy",
      medium: "Medium",
      hard: "Hard",
      solvedOnly: "Solved only",
      unsolvedOnly: "Unsolved only",
      statusCol: "Status",
      titleCol: "Title",
      difficultyCol: "Difficulty",
      categoryCol: "Category",
      xpCol: "XP",
      acceptanceCol: "Acceptance",
      actionCol: "Action",
      solveBtn: "Solve →",
      prevPage: "Previous",
      nextPage: "Next",
      page: "Page",
    },
    workspace: {
      problemDesc: "Description",
      inputFormat: "Input Format",
      outputFormat: "Output Format",
      examples: "Examples",
      constraints: "Constraints",
      input: "Input",
      expectedOutput: "Expected Output",
      explanation: "Explanation",
      fontSize: "Font size",
      copyCode: "Copy",
      copied: "Copied!",
      resetCode: "Reset",
      fullscreen: "Fullscreen",
      testResults: "Test Results",
      console: "Console",
      runCode: "Run Code",
      running: "Running…",
      submitCode: "Submit",
      submitting: "Submitting…",
      accepted: "Accepted",
      wrongAnswer: "Wrong Answer",
      runtimeError: "Runtime Error",
      timeLimit: "Time Limit Exceeded",
      congrats: "Congratulations! Problem solved!",
      xpGained: "awarded!",
      coinsGained: "coins",
      testCase: "Test Case",
      passed: "Passed",
      failed: "Failed",
      expected: "Expected",
      actual: "Actual",
      runtime: "Runtime",
      memory: "Memory",
    },
    leaderboard: {
      title: "Leaderboard",
      subtitle: "Global ranking of competitive coders",
      allTime: "All Time",
      weekly: "Weekly",
      monthly: "Monthly",
      searchUser: "Search user…",
      rank: "Rank",
      coder: "Coder",
      level: "Level",
      xp: "XP",
      solved: "Solved",
      streak: "Streak",
    },
    achievements: {
      title: "Achievements & Badges",
      subtitle: "Unlock badges as you solve problems and maintain streaks",
      unlocked: "Unlocked",
      locked: "Locked",
      progress: "Progress",
    },
    settings: {
      title: "Settings",
      subtitle: "Manage your profile and preferences",
      languageSection: "System Language",
      uzbekLang: "O'zbek tili (UZ)",
      englishLang: "English (EN)",
      preferredLanguage: "Preferred Coding Language",
      bio: "Bio",
      github: "GitHub Username",
      saveChanges: "Save changes",
      saving: "Saving…",
      savedSuccess: "Settings saved successfully!",
    },
    profile: {
      title: "Profile",
      editSettings: "Settings",
      activity: "Activity",
      recentSubmissions: "Recent Submissions",
      stats: "Statistics",
      acceptanceRate: "Acceptance Rate",
    },
    submissions: {
      title: "Submissions",
      subtitle: "Full history of your code executions and judging results",
      problem: "Problem",
      status: "Status",
      language: "Language",
      runtime: "Runtime",
      memory: "Memory",
      date: "Date",
    },
    auth: {
      loginTitle: "Sign in",
      loginSubtitle: "Sign in to continue competing",
      registerTitle: "Join CodeArena",
      registerSubtitle: "Create your competitive coding profile",
      username: "Username",
      email: "Email",
      password: "Password",
      signInBtn: "Sign in",
      signUpBtn: "Create account",
      noAccount: "Don't have an account?",
      alreadyAccount: "Already have an account?",
      refCode: "Referral code (optional)",
      refBonus: "Join with a referral code and get a +100 coin bonus!",
    },
    shop: {
      title: "Coin Shop",
      subtitle: "Earn coins by solving problems and spend them on unique items",
      balance: "Your balance",
      howToEarn: "How to earn coins",
      earnEasy: "Easy problem",
      earnMedium: "Medium problem",
      earnHard: "Hard problem",
      earnInvite: "Invite a friend",
      all: "All",
      frame: "Avatar frames",
      title_: "Titles",
      theme: "IDE themes",
      booster: "Boosters",
      buy: "Buy",
      buying: "Buying…",
      owned: "Owned",
      equip: "Equip",
      unequip: "Unequip",
      equipped: "Equipped",
      notEnough: "Not enough coins",
      history: "Coin history",
      noHistory: "No coin activity yet.",
      shields: "Streak shields",
      loginToBuy: "Log in to buy",
      rarity: { common: "Common", rare: "Rare", epic: "Epic", legendary: "Legendary" },
    },
    referral: {
      title: "Invite friends",
      subtitle: "Get +500 coins for every friend you invite!",
      yourCode: "Your referral code",
      yourLink: "Your invite link",
      copy: "Copy",
      copied: "Copied!",
      step1: "Send the link to a friend",
      step2: "They sign up and get +100 coins",
      step3: "You instantly get +500 coins",
      invited: "Friends invited",
      earned: "Coins earned",
      friends: "Your invited friends",
      noFriends: "Nobody has joined with your invite yet. Share your link!",
      joined: "joined",
    },
  },
};

type LangState = {
  lang: Language;
  t: typeof translations["uz"];
  setLang: (lang: Language) => void;
  toggleLang: () => void;
};

export const useLang = create<LangState>((set, get) => {
  const initialLang: Language =
    typeof window !== "undefined" && localStorage.getItem("ca_lang") === "en"
      ? "en"
      : "uz";

  return {
    lang: initialLang,
    t: translations[initialLang],
    setLang: (lang: Language) => {
      if (typeof window !== "undefined") {
        localStorage.setItem("ca_lang", lang);
      }
      set({ lang, t: translations[lang] });
    },
    toggleLang: () => {
      const next = get().lang === "uz" ? "en" : "uz";
      get().setLang(next);
    },
  };
});
